### PR TITLE
Fixes #931

### LINKED ISSUE #931: [BUG] unsatisfiable constraints: python2-2.7.16-r2 breaks world[python=2.7.16-r1]
## Environment
Please provide as many details as you can:
Ubuntu 19.10
image

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: anything in master branch at 16/02/2020

## Steps to Reproduce
1. git clone https://github.com/formio/formio.git
2. cd formio/
3. npm install
4. docker-compose up

## Observed behavior
Creating network "formio_default" with the default driver
Creating volume "formio_mdb-data" with default driver
Pulling mongo (mongo:4.1)...
4.1: Pulling from library/mongo
7413c47ba209: Pull complete
0fe7e7cbb2e8: Pull complete
1d425c982345: Pull complete
344da5c95cec: Pull complete
3c705a3e5fce: Pull complete
f6508c5fc358: Pull complete
1798ab2eeee4: Pull complete
aa98b7988869: Pull complete
c3407a29f56d: Pull complete
97df9363920d: Pull complete
adab802cb21b: Pull complete
32e764769299: Pull complete
98184930f8ea: Pull complete
Digest: sha256:8005da1dcf3d2ff800f9ccb339012522e3c93c12e1394edab54336991ddc8a1a
Status: Downloaded newer image for mongo:4.1
Building formio
Step 1/11 : FROM node:lts-alpine3.10
lts-alpine3.10: Pulling from library/node
4167d3e14976: Pull complete
88e051f8b785: Pull complete
0b99f66d422a: Pull complete
6f8dbab757a5: Pull complete
Digest: sha256:c4d08dcba34e7ac0a1f6d914cfc975c5f0d168d9cacadab123a24efca3ee86dc
Status: Downloaded newer image for node:lts-alpine3.10
 ---> 48ae9395145d
Step 2/11 : WORKDIR /app
 ---> Running in 43b6cba5a1ed
Removing intermediate container 43b6cba5a1ed
 ---> aaf5d1090011
Step 3/11 : RUN apk update &&     apk upgrade &&     apk add python=2.7.16-r1 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0
 ---> Running in 2198f24366df
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.4-15-g5600c80ab9 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.4-7-g6ee081a8fb [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10343 distinct packages available
OK: 7 MiB in 16 packages
ERROR: unsatisfiable constraints:
  python2-2.7.16-r2:
    breaks: world[python=2.7.16-r1]
ERROR: Service 'formio' failed to build: The command '/bin/sh -c apk update &&     apk upgrade &&     apk add python=2.7.16-r1 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0' returned a non-zero code: 1

## Solution:
In Dockerfile, line 14, change the line:
    apk add python=2.7.16-r1 && \
to 
    apk add python=2.7.16-r2 && \

run docker-compose up again, it is done.
I will tried  to create a PR but I think I don't have permission to create a branch.

### PR DESCRIPTION
**Pull request by staadecker**
Attempt to fix #931 . Should be tested to verify that the version change does not break anything (I haven't tested).

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
I don't think it makes sense to keep repin these versions to newer ones to have "immutable" builds when this pinning itself causes builds to fail each time the Alpine image gets updated with newer packages.

**Comment by staadecker** [comment]
@rimas-kudelis yes fair enough, is there a better solution? I'm not well aware of the best practices.

**Comment by rimas-kudelis** [comment]
@staadecker the base image already has Python by default (that's what conflicts with the older version when `apk` tries to install it), so that line in question could just be removed altogether, and everything would just work.

Whether form.io maintainers would accept a fix like that or if they want it fixed differently is the real question. :)

**Comment by staadecker** [comment]
Understood! We'll see what the maintainers would like. Happy to edit my PR accordingly.

**Comment by randallknutson** [comment]
We don't typically use the docker file in this repo. What would you all like? My preference would probably be to remove the line pinning python if the default solution works.

**Comment by staadecker** [comment]
@randallknutson that works for me

**Pull request merged**
