### PR TITLE
Return anonymous submissions in index requests from administrators

### PR DESCRIPTION
**Pull request by douglaselee**
Otherwise who can see them?

### CODE REVIEW

**Comment by travist** [comment]
This seems to indicate a bug in our permission check. For administrators, it should not matter who the owner is if they have read access to the submission. If this does not work, then this would indicate it is broken somewhere else.

**Comment by douglaselee** [comment]
Hey @travist,

If you try the index request as administrator and there are some anonymous submissions you can see the difference with and without this change.

**Comment by douglaselee** [comment]
I think you will only see the difference if some submissions of the given type have explicit access set.

Would seem to make sense to check `req.admin` first thing in `flagRequestAsSubmissionResourceAccess` function in `permissionHandler.js`.  Unfortunately `req.admin` isn't set until later in `permissionHandler.js`.

Could or in `req.admin` to condition on line 12 of `submissionResourceAccessFilter.js` so administrators see all submissions and not just those they own or which are anonymous.

**Comment by douglaselee** [comment]
Modified as described above so administrators will see all submissions regardless of ownership or explicit access.

**Comment by travist** [comment]
Hey @douglaselee. 

Thanks again for adding this. I think to help provide some context of this, we would like to see a "test" that fails without this change. This will allow us to see what exactly this is fixing as well as ensure that once we pull this in, it will never break in the future. Once we get that, we will include it in the next release.

Thanks,

Travis.

**Comment by douglaselee** [comment]
Hey @travist,

Happy to help.  Sorry if protocol was breached by bringing up security stuff in github.  Hope that's not a problem since this is a case of too much security rather than too little.

Will try to whip up test for it.  May be a little involved since it will require a database containing at least one submission with explicit access set like
```
...
    "access" : [ 
        {
            "type" : "read",
            "resources" : [ 
                ObjectId("590cd461557f061e6c9295fc")
            ]
        }, 
        {
            "type" : "write",
            "resources" : [ 
                ObjectId("590cd461557f061e6c9295fc")
            ]
        }
    ],
...
```

Going to be away most of December but will get to it ASAP.

Thanks for your patience,
Doug

**Comment by travist** [comment]
Looking at your recent changes to this pull request, this seems reasonable now. We will pull it in for the next release.

**Comment by douglaselee** [comment]
Thanks Travis.

**Pull request merged**
