### PR TITLE
allow usage of Unauthorized certificates

### PR DESCRIPTION
**Pull request by sl45sms**
Set the flag tls -> rejectUnauthorized to false, if you wont to allow usage of self signed certificates on smtp server

### CODE REVIEW

**Comment by travist** [comment]
Looks good! I will pull this into the next release.

**Comment by sl45sms** [comment]
Thanks!

**Comment by travist** [comment]
I ended up changing the name of the configuration on this to make it a "truthy" variable and also placed it on the root of the smtp configuration. The new variable name is called

```email.smtp.allowUnauthorizedCerts``` 

which is much more descriptive, and if set to TRUE, it will add this configuration to the settings.

**Comment by sl45sms** [comment]
Great, yes it is much more descriptive!

**Pull request merged**
