### PR TITLE
Added Merge Component Schema action type.

### PR DESCRIPTION
**Pull request by YuryRybakSoftensity**

### CODE REVIEW

**Comment by rae-alisyed** [comment]
Hello, this is Ali Syed from the REALTORS® Association of Edmonton. 

I am wondering if you are able to add the spec requirement for this PR.

**Comment by randallknutson** [comment]
Hi Ali,

What is it that you need to know? This action allows merging in new options to any component as part of the field logic system. We can help you do whatever it is you need to do to modify the component using this.

**Comment by rae-alisyed** [comment]
Not sure if I was directed to the right PR.. But I was under the impression there was custom code being written to address our specific business requirement. @wag110894 linked this PR to our mini-project.

**Comment by wag110894** [comment]
Hello Ali,
Apologies for the confusion.
This is the correct PR to trigger actions based on submissions states like “draft” and “submitted". 

This was a platform enhancement and not custom development.

Sorry again for any confusion.

**Comment by rae-alisyed** [comment]
Hi @wag110894 
,
So going back to our specific requirement; Are we able to say when user 1 saves the form as draft, it triggers an email action to another anonymous user, and in the email is a direct URL to the form in draft mode (with the information filled out)?

Thanks.

**Pull request merged**
