### PR TITLE
Improvement/replaced deprecated request package

### PR DESCRIPTION
**Pull request by airarrazaval**
Fix for issue https://github.com/formio/formio/issues/972

### CODE REVIEW

**Comment by travist** [comment]
My only issue with this is that we have customers today that sit behind a Proxy and use the Request.js HTTP_PROXY environment variables to get around this. We would need to re-implement that with this change in order to accept this.

**Comment by travist** [comment]
Thank you for the contribution.

**Comment by travist** [comment]
Maybe we could add a shim file that includes the following.

https://github.com/node-fetch/node-fetch/issues/195

**Comment by airarrazaval** [comment]
@travist I created the node-fetch shim with support for http(s) proxy.  It is also supporting the following env variables:

- HTTP_PROXY: proxy configuration for http requests
- HTTPS_PROXY: proxy configuration for https requests
- NO_PROXY: comma separated list of domain parts to exclude from proxying
- NODE_TLS_REJECT_UNAUTHORIZED: allow invalid TLS certificates (such as self signed)

At first I thought of allowing http agent override (defined by user) which could cause to bypass proxy configuration, but on a second though and taking security into account, I removed that option (if a sever defines a proxy, then it should be used).  Also, now you will need to explicitly define `NODE_TLS_REJECT_UNAUTHORIZED = '0'` to allow invalid TLS certificates as it is also a security risk to allow this by default.

**Comment by travist** [comment]
This is fantastic! Thank you for your efforts!  We will include this in the 2.x branch of this library which is still in beta, but will eventually become an official release.

**Pull request merged**
