### PR TITLE
Translate action dropdown items

### PR DESCRIPTION
**Pull request by douglaselee**
In templates for select components.
Many of these items will come from the names of resources or fields created by the users in their own languages and not really need translation.
Others like the User and Admin resources and their fields are created by install and could stand to be translated.

### CODE REVIEW

**Comment by travist** [comment]
The only problem with this is I believe this locks us into Angular 1. We may need to figure out a way to do this so it is also compatible with the core renderer as well before we can accept this into the core API platform.

**Comment by douglaselee** [comment]
Hey Travis,

I'm hoping that the formioTranslate filter will survive the conversion of ngFormio to use the core renderer.  Then if the builder and action editor still depend on ngFormio all of these `... | formioTranslate` instances should still work.  Are you planning to convert the builder or helper away from Angular 1 any time soon?

**Comment by travist** [comment]
We are using Lodash templates for all interpolation in the core renderer. 

https://lodash.com/docs/4.17.4#template

I am not sure if it supports filters, but it does support execution of javascript using ```{% %}```. We may be able to support this in core by exposing the ```formioTranslate``` method, and then doing a pre-search for ```| formioTranslate``` and then change that to the method call. That would slow down the interpolation quite a bit.

**Comment by douglaselee** [comment]
Hey Travis,

Thanks for clarification and thoughts on possible solution.  What was I thinking?  Of course when ngFormio is converted to use core renderer this wouldn't work even if action editor still depends on ngFormio.  Maybe if core select component simply invoked the core translator on the result of the interpolation none of this would be necessary.

There may be users out there with templates like `<span>{{ item.label | formioTranslate }}</span>` in their own forms (or the React, Angular 2... counterparts).  I suppose they will need to update their forms when ngFormio and its counterparts are converted to use core renderer.

Would be great if ngFormio continues to include current formioTranslate filter for the benefit of the builder, helper and apps which use it for translating lots of stuff that has nothing to do with form rendering.  At least as long as those benificiaries continue to depend on ngFormio.

**Comment by travist** [comment]
We will do what we can in the core renderer. I am hesitant to include this since this will handcuff the formio/formio server to Angular 1.x until we fix the core renderer to support filters.

**Comment by douglaselee** [comment]
Thanks Travis.  Go ahead and close this one if you'd like.  Will figure something out when ngFormio is converted to use the core renderer.

**Comment by travist** [comment]
Closing for now. We will figure out how to get this in place at a later time.

**Pull request closed without merging**
