### PR TITLE
Fix role assignment for existing resources

### PR DESCRIPTION
**Pull request by douglaselee**
For me the resource is not yet a string but an object whose _id is a string from which the resource can be loaded

### CODE REVIEW

**Comment by zackurben** [comment]
@douglaselee do you mind explaining what your issue is?

This code is meant to have `resource` as an object: https://github.com/douglaselee/formio/blob/b5a20c014b2f8b99951b1c766e3b6d225601a9e3/src/actions/RoleAction.js#L342-L344

however, if it isn't, and its a string, it loads the submission first, the prior if. How are you getting to this point, perhaps there is a better fix?

**Comment by douglaselee** [comment]
Hi Zack,

When assigning a role to a new resource the _resource_ variable is a model object with a save function which the updateModel function will call.

When assigning a role to an existing resource the _resource_ variable is simply the resource object with no save function so updateModel does nothing.

To reproduce simply create a form which contains an action to assign a role to an existing resource.

The intent of my fix is to replace _resource_ with the resource's id so the following code will load the updatable model object.

**Comment by travist** [comment]
I am ok with this change. I will be releasing a new version of formio/formio this weekend which will include all your changes. Thanks for the help @douglaselee!

**Comment by travist** [comment]
Pulling this into the 1.17.0 build.

**Comment by douglaselee** [comment]
Happy to help Travis, thank you for FormIO!  I'm learning a lot by reading your code.

**Pull request closed without merging**
